"use client";
import {useEffect,useMemo,useState} from "react";

const SPORTS=["All","NFL","NCAAF","MLB","NBA","NCAAB","WNBA","NHL","Soccer","Tennis"];
const LABEL={All:"All Sports",NFL:"NFL",NCAAF:"College Football",MLB:"MLB",NBA:"NBA",NCAAB:"College Basketball",WNBA:"WNBA",NHL:"NHL",Soccer:"Soccer",Tennis:"Tennis"};
const seed=[
 {day:1,date:"2026-09-04",team:"Michigan State",opponent:"Toledo",odds:-405,result:"WIN"},
 {day:2,date:"2026-09-05",team:"Auburn",opponent:"Baylor",odds:-300,result:"WIN"},
 {day:3,date:"2026-09-05",team:"LSU",opponent:"Clemson",odds:-500,result:"WIN"}
];
const fmtMoney=n=>`${n>=0?"+":""}$${Number(n).toFixed(2)}`;
const implied=o=>o<0?(-o/(-o+100))*100:(100/(o+100))*100;
function Icon({type}){const p={home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></>,list:<><path d="M8 6h12M8 12h12M8 18h12"/><path d="M4 6h.01M4 12h.01M4 18h.01"/></>,chart:<><path d="M4 19V5M4 19h16"/><path d="m7 15 3-4 3 2 5-7"/></>,calendar:<><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19 15l1 1-2 2-1-1a7 7 0 0 1-3 1v2h-3v-2a7 7 0 0 1-3-1l-1 1-2-2 1-1a7 7 0 0 1-1-3H3v-3h2a7 7 0 0 1 1-3L5 7l2-2 1 1a7 7 0 0 1 3-1V3h3v2a7 7 0 0 1 3 1l1-1 2 2-1 1a7 7 0 0 1 1 3h2v3h-2a7 7 0 0 1-1 3Z"/></>,spark:<><path d="M12 3l1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3Z"/><path d="M19 14l.7 2.3L22 17l-2.3.7L19 20l-.7-2.3L16 17l2.3-.7L19 14Z"/></>,refresh:<><path d="M20 11a8 8 0 0 0-14.7-3L4 10"/><path d="M4 5v5h5M4 13a8 8 0 0 0 14.7 3L20 14"/><path d="M20 19v-5h-5"/></>,shield:<><path d="M12 3 20 6v5c0 5-3.4 8.2-8 10-4.6-1.8-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>};return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{p[type]}</svg>}
function Button({children,onClick,active}){return <button className={active?"pill active":"pill"} onClick={onClick}>{children}</button>}

export default function App(){
 const [tab,setTab]=useState("home"),[sport,setSport]=useState("All"),[games,setGames]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[lastUpdated,setLastUpdated]=useState(null);
 const [bankroll,setBankroll]=useState(83.29),[starting,setStarting]=useState(40),[history,setHistory]=useState(seed),[challenge,setChallenge]=useState(30),[settings,setSettings]=useState({stake:25,auto:true});
 const [month,setMonth]=useState(new Date(2026,8,1)),[selected,setSelected]=useState(null),[notice,setNotice]=useState("");
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("lb_state")||"null");if(s){setBankroll(s.bankroll);setStarting(s.starting);setHistory(s.history);setChallenge(s.challenge);setSettings(s.settings||{stake:25,auto:true})}}catch{}},[]);
 useEffect(()=>{localStorage.setItem("lb_state",JSON.stringify({bankroll,starting,history,challenge,settings}))},[bankroll,starting,history,challenge,settings]);
 async function refresh(){setLoading(true);setError("");try{const r=await fetch("/api/odds?ts="+Date.now(),{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"Live odds unavailable");setGames(d.games||[]);setLastUpdated(d.updatedAt);if(d.bestPick) setNotice(`Automatic #1 pick: ${d.bestPick.selection} ${d.bestPick.bestOdds}`);else setNotice("No qualifying play right now.")}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[]);
 const qual=useMemo(()=>games.flatMap(g=>(g.qualifying||[]).map(q=>({...g,bestOdds:q.price,selection:q.name,book:q.book}))).sort((a,b)=>implied(b.bestOdds)-implied(a.bestOdds)),[games]);
 const top=qual[0]||null;const visible=sport==="All"?games:games.filter(g=>g.sport===sport);
 const wins=history.filter(x=>x.result==="WIN").length,losses=history.filter(x=>x.result==="LOSS").length,profit=bankroll-starting,roi=starting?profit/starting*100:0;
 function setPage(x){setTab(x);window.scrollTo({top:0,behavior:"smooth"})}
 function settle(result){if(!top)return;const stake=Math.min(Number(settings.stake)||0,bankroll);if(stake<=0)return;const odds=top.bestOdds;const gain=result==="WIN"?stake*(odds<0?100/(-odds):odds/100):-stake;setBankroll(b=>Math.max(0,b+gain));setHistory(h=>[{day:h.length+1,date:new Date().toISOString().slice(0,10),team:top.selection,opponent:top.selection===top.home?top.away:top.home,odds,result},...h]);setNotice(`${result}: ${top.selection} recorded`)}
 function calendar(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),n=new Date(y,m+1,0).getDate();const cells=Array(first).fill(null).concat(Array.from({length:n},(_,i)=>i+1));const map={};history.forEach(h=>(map[h.date]??=[]).push(h));return <><div className="cal card"><div className="calhead"><button onClick={()=>setMonth(new Date(y,m-1,1))}>‹</button><h2>{month.toLocaleString([],{month:"long",year:"numeric"})}</h2><button onClick={()=>setMonth(new Date(y,m+1,1))}>›</button></div><div className="week">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><span key={x}>{x}</span>)}</div><div className="grid">{cells.map((d,i)=>{if(!d)return <div key={i} className="blank"/>;const key=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,items=map[key]||[],r=items[0]?.result;return <button key={key} className={`day ${r==="WIN"?"win":r==="LOSS"?"loss":""} ${selected===key?"selected":""}`} onClick={()=>setSelected(key)}><b>{d}</b>{r&&<small>{r}</small>}</button>})}</div><div className="legend"><span>● Win</span><span>● Loss</span><span>○ No bet</span></div></div>{selected&&map[selected]?.length?<div className="card detail">{map[selected].map((h,i)=><div key={i}><b>{h.team}</b> <span>vs {h.opponent}</span><strong className={h.result.toLowerCase()}>{h.result}</strong><small>{h.odds} • {h.date}</small></div>)}</div>:null}</>}
 function home(){return <><section className="hero"><div><label><Icon type="spark"/> LIVE SPORTSBOOK</label><h1>Every game.<br/><em>One system.</em></h1><p>Live odds across the slate with your permanent -200 to -500 moneyline rule.</p></div><img src="/lifetimebets-logo.png" alt="LB"/></section><div className="metrics"><div><span>Bankroll</span><b>${bankroll.toFixed(2)}</b></div><div><span>Record</span><b>{wins}-{losses}</b></div><div><span>ROI</span><b>{roi>=0?"+":""}{roi.toFixed(1)}%</b></div><div><span>Streak</span><b>W{wins}</b></div></div><PickCard top={top} loading={loading} refresh={refresh} auto={true}/><section className="sectionrow"><div><label>FULL SLATE</label><h2>{LABEL[sport]}</h2></div><span>{visible.length} games</span></section><div className="pills">{SPORTS.map(s=><Button key={s} active={sport===s} onClick={()=>setSport(s)}>{LABEL[s]}</Button>)}</div><div className="games">{visible.length?visible.map(g=><Game key={g.eventId} g={g}/>):<Empty text={loading?"Loading every sport…":"No games returned. Add your Odds API key in Vercel."}/>}</div></>}
 function picks(){return <><Title t="Today's Pick" s="The app selects the #1 qualifying moneyline automatically."/><PickCard top={top} loading={loading} refresh={refresh} auto/><div className="card"><label>SELECTION RULE</label><div className="rules">{["Moneyline only","-200 through -500","All supported sports","Highest implied probability first","No qualifying line = NO BET"].map(x=><p key={x}><Icon type="shield"/>{x}</p>)}</div></div>{top&&<div className="actions"><button onClick={()=>settle("WIN")}>Mark Win</button><button onClick={()=>settle("LOSS")} className="secondary">Mark Loss</button></div>}</>}
 function stats(){return <><Title t="Stats" s="Track performance and see every official betting day."/><div className="metrics four"><div><span>Profit</span><b className={profit>=0?"good":"bad"}>{fmtMoney(profit)}</b></div><div><span>Win Rate</span><b>{history.length?(wins/history.length*100).toFixed(1):"0.0"}%</b></div><div><span>Record</span><b>{wins}-{losses}</b></div><div><span>Avg Odds</span><b>{history.length?Math.round(history.reduce((a,x)=>a+x.odds,0)/history.length):0}</b></div></div>{calendar()}<div className="card"><label>BET HISTORY</label>{history.map(h=><div className="history" key={h.date+h.team}><div><b>{h.team}</b><span>{h.date} • vs {h.opponent}</span></div><strong>{h.odds}</strong><em className={h.result.toLowerCase()}>{h.result}</em></div>)}</div></>}
 function challengePage(){const progress=Math.min(100,history.length/challenge*100);return <><Title t="Challenge" s={`${challenge}-day bankroll challenge.`}/><div className="challenge card"><b>{history.length}<small>/{challenge}</small></b><div><h2>Days completed</h2><p>{Math.max(0,challenge-history.length)} days remaining</p></div></div><div className="progress"><i style={{width:`${progress}%`}}/></div><div className="card"><label>CHALLENGE RULES</label><p>One official play per day. The system can say NO BET. Results only count when you mark the automatic pick as Win or Loss.</p></div></>}
 function settingsPage(){return <><Title t="Settings" s="Control your bankroll, stake and challenge."/><div className="card"><div className="setting"><span>Starting bankroll</span><input type="number" value={starting} onChange={e=>setStarting(Number(e.target.value)||0)}/></div><div className="setting"><span>Current bankroll</span><input type="number" value={bankroll} onChange={e=>setBankroll(Number(e.target.value)||0)}/></div><div className="setting"><span>Daily stake</span><input type="number" value={settings.stake} onChange={e=>setSettings({...settings,stake:Number(e.target.value)||0})}/></div><div className="setting"><span>Challenge days</span><input type="number" value={challenge} onChange={e=>setChallenge(Number(e.target.value)||30)}/></div></div><div className="card"><label>ODDS RULE</label><p>Moneyline only • -200 to -500 • all sports • automatic #1 selection.</p><p className="muted">Live odds are supplied by The Odds API through the secure server route.</p></div></>}
 let body=tab==="home"?home():tab==="picks"?picks():tab==="stats"?stats():tab==="challenge"?challengePage():settingsPage();
 return <><header><button className="brand" onClick={()=>setPage("home")}><img src="/lifetimebets-logo.png"/><span>LIFETIMEBETS</span></button><button className="refresh" onClick={refresh} disabled={loading}><span className={loading?"spin":""}><Icon type="refresh"/></span></button></header><main>{body}</main><nav><Nav active={tab==="home"} onClick={()=>setPage("home")} icon={<Icon type="home"/>} label="Home"/><Nav active={tab==="picks"} onClick={()=>setPage("picks")} icon={<Icon type="spark"/>} label="Picks"/><Nav active={tab==="stats"} onClick={()=>setPage("stats")} icon={<Icon type="chart"/>} label="Stats"/><Nav active={tab==="challenge"} onClick={()=>setPage("challenge")} icon={<Icon type="calendar"/>} label="Challenge"/><Nav active={tab==="settings"} onClick={()=>setPage("settings")} icon={<Icon type="settings"/>} label="Settings"/></nav>{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}{error&&<div className="error">{error}</div>}</>}
function Nav({active,onClick,icon,label}){return <button className={active?"nav active":"nav"} onClick={onClick}>{icon}<span>{label}</span></button>}
function Title({t,s}){return <div className="title"><label>LIFETIMEBETS</label><h1>{t}</h1><p>{s}</p></div>}
function Empty({text}){return <div className="empty"><Icon type="shield"/><b>{text}</b></div>}
function PickCard({top,loading,refresh,auto}){return <section className="card pick"><div className="cardtop"><div><label>{auto?"TODAY'S #1 PLAY • AUTOMATIC":"TOP QUALIFYING PLAY"}</label><h2>{top?top.selection:loading?"Scanning live slate…":"NO BET"}</h2></div><button onClick={refresh}><Icon type="refresh"/></button></div>{top?<><div className="match">{top.away} <span>at</span> {top.home}</div><div className="pickline"><b>{top.bestOdds}</b><div><strong>{implied(top.bestOdds).toFixed(1)}% implied</strong><span>{top.sportTitle} • {top.book||"Best available"}</span></div></div><div className="analysis"><Icon type="shield"/><span><b>Why #1:</b> highest implied probability among all qualifying moneylines returned by the live slate.</span></div></>:<Empty text={loading?"Scanning every supported sport…":"No qualifying play right now."}/>}</section>}
function Game({g}){return <article className="game"><div><label>{g.sportTitle}</label><b>{g.away}</b><b>{g.home}</b><small>{new Date(g.commence).toLocaleString([], {weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</small></div><div className="lines">{g.lines?.slice(0,2).map(x=><span className={x.price>=-500&&x.price<=-200?"line q":"line"} key={x.name}><small>{x.name}</small><strong>{x.price}</strong>{x.price>=-500&&x.price<=-200?<em>QUALIFY</em>:null}</span>)}</div></article>}
